export const FETCH_INGREDIENTS = "FETCH_INGREDIENTS";
export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENT = "SET_INGREDIENT";
export const FETCH_INGREDIENT_FAILED = "FETCH_INGREDIENT_FAILED";

export const PURCHASE_BURGER_INIT = "PURCHASE_BURGER_INIT";
export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";
export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL";
export const PURCHASE_INIT = "PURCHASE_INIT";

export const FETCH_ORDERS_START = "FETCH_ORDER_START";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDER_SUCCESS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDER_FAIL";
export const FETCH_ORDERS_INIT = "FETCH_ORDER_INIT";

export const AUTH_USER = "AUTH_USER";
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_CHECK_TIME_OUT = "AUTH_CHECK_TIME_OUT";
export const AUTH_INITIATE_LOG_OUT = "AUTH_INITIATE_LOG_OUT";
export const AUTH_CHECK_LOGIN_STATE = "AUTH_CHECK_LOGIN_STATE";
export const LOG_OUT = "LOG_OUT";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
